In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv("D:\Datasets\CarPrice.csv")
dataset

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [5]:
dataset.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [6]:
data=dataset[["highwaympg","price"]]
data

     highwaympg    price
0            27  13495.0
1            27  16500.0
2            26  16500.0
3            30  13950.0
4            22  17450.0
..          ...      ...
200          28  16845.0
201          25  19045.0
202          23  21485.0
203          27  22470.0
204          25  22625.0

[205 rows x 2 columns]

In [7]:
x=data.iloc[:,[0]].values
x

array([[27],
       [27],
       [26],
       [30],
       [22],
       [25],
       [25],
       [25],
       [20],
       [22],
       [29],
       [29],
       [28],
       [28],
       [25],
       [22],
       [22],
       [20],
       [53],
       [43],
       [43],
       [41],
       [38],
       [30],
       [38],
       [38],
       [38],
       [30],
       [30],
       [24],
       [54],
       [38],
       [42],
       [34],
       [34],
       [34],
       [34],
       [33],
       [33],
       [33],
       [33],
       [28],
       [31],
       [29],
       [43],
       [43],
       [29],
       [19],
       [19],
       [17],
       [31],
       [38],
       [38],
       [38],
       [38],
       [23],
       [23],
       [23],
       [23],
       [32],
       [32],
       [32],
       [32],
       [42],
       [32],
       [27],
       [39],
       [25],
       [25],
       [25],
       [25],
       [18],
       [18],
       [16],
       [16],
       [24],
       [41],
       [38],
       [38],
       [30],
       [30],
       [32],
       [24],
       [24],
       [24],
       [32],
       [32],
       [30],
       [30],
       [37],
       [50],
       [37],
       [37],
       [37],
       [37],
       [37],
       [37],
       [37],
       [37],
       [34],
       [34],
       [22],
       [22],
       [25],
       [25],
       [23],
       [25],
       [24],
       [33],
       [24],
       [25],
       [24],
       [33],
       [24],
       [25],
       [24],
       [33],
       [24],
       [41],
       [30],
       [38],
       [38],
       [38],
       [30],
       [24],
       [27],
       [25],
       [25],
       [25],
       [28],
       [31],
       [31],
       [28],
       [28],
       [28],
       [28],
       [26],
       [26],
       [36],
       [31],
       [31],
       [37],
       [33],
       [32],
       [25],
       [29],
       [32],
       [31],
       [29],
       [23],
       [39],
       [38],
       [38],
       [37],
       [32],
       [32],
       [37],
       [37],
       [36],
       [47],
       [47],
       [34],
       [34],
       [34],
       [34],
       [29],
       [29],
       [30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [34],
       [33],
       [32],
       [32],
       [32],
       [24],
       [24],
       [24],
       [24],
       [46],
       [34],
       [46],
       [34],
       [34],
       [42],
       [32],
       [29],
       [29],
       [24],
       [38],
       [31],
       [28],
       [28],
       [28],
       [28],
       [22],
       [22],
       [28],
       [25],
       [23],
       [27],
       [25]], dtype=int64)

In [8]:
y=data.iloc[:,[-1]].values
y

array([[13495.   ],
       [16500.   ],
       [16500.   ],
       [13950.   ],
       [17450.   ],
       [15250.   ],
       [17710.   ],
       [18920.   ],
       [23875.   ],
       [17859.167],
       [16430.   ],
       [16925.   ],
       [20970.   ],
       [21105.   ],
       [24565.   ],
       [30760.   ],
       [41315.   ],
       [36880.   ],
       [ 5151.   ],
       [ 6295.   ],
       [ 6575.   ],
       [ 5572.   ],
       [ 6377.   ],
       [ 7957.   ],
       [ 6229.   ],
       [ 6692.   ],
       [ 7609.   ],
       [ 8558.   ],
       [ 8921.   ],
       [12964.   ],
       [ 6479.   ],
       [ 6855.   ],
       [ 5399.   ],
       [ 6529.   ],
       [ 7129.   ],
       [ 7295.   ],
       [ 7295.   ],
       [ 7895.   ],
       [ 9095.   ],
       [ 8845.   ],
       [10295.   ],
       [12945.   ],
       [10345.   ],
       [ 6785.   ],
       [ 8916.5  ],
       [ 8916.5  ],
       [11048.   ],
       [32250.   ],
       [35550.   ],
       [36000.   ],
       [ 5195.   ],
       [ 6095.   ],
       [ 6795.   ],
       [ 6695.   ],
       [ 7395.   ],
       [10945.   ],
       [11845.   ],
       [13645.   ],
       [15645.   ],
       [ 8845.   ],
       [ 8495.   ],
       [10595.   ],
       [10245.   ],
       [10795.   ],
       [11245.   ],
       [18280.   ],
       [18344.   ],
       [25552.   ],
       [28248.   ],
       [28176.   ],
       [31600.   ],
       [34184.   ],
       [35056.   ],
       [40960.   ],
       [45400.   ],
       [16503.   ],
       [ 5389.   ],
       [ 6189.   ],
       [ 6669.   ],
       [ 7689.   ],
       [ 9959.   ],
       [ 8499.   ],
       [12629.   ],
       [14869.   ],
       [14489.   ],
       [ 6989.   ],
       [ 8189.   ],
       [ 9279.   ],
       [ 9279.   ],
       [ 5499.   ],
       [ 7099.   ],
       [ 6649.   ],
       [ 6849.   ],
       [ 7349.   ],
       [ 7299.   ],
       [ 7799.   ],
       [ 7499.   ],
       [ 7999.   ],
       [ 8249.   ],
       [ 8949.   ],
       [ 9549.   ],
       [13499.   ],
       [14399.   ],
       [13499.   ],
       [17199.   ],
       [19699.   ],
       [18399.   ],
       [11900.   ],
       [13200.   ],
       [12440.   ],
       [13860.   ],
       [15580.   ],
       [16900.   ],
       [16695.   ],
       [17075.   ],
       [16630.   ],
       [17950.   ],
       [18150.   ],
       [ 5572.   ],
       [ 7957.   ],
       [ 6229.   ],
       [ 6692.   ],
       [ 7609.   ],
       [ 8921.   ],
       [12764.   ],
       [22018.   ],
       [32528.   ],
       [34028.   ],
       [37028.   ],
       [31400.5  ],
       [ 9295.   ],
       [ 9895.   ],
       [11850.   ],
       [12170.   ],
       [15040.   ],
       [15510.   ],
       [18150.   ],
       [18620.   ],
       [ 5118.   ],
       [ 7053.   ],
       [ 7603.   ],
       [ 7126.   ],
       [ 7775.   ],
       [ 9960.   ],
       [ 9233.   ],
       [11259.   ],
       [ 7463.   ],
       [10198.   ],
       [ 8013.   ],
       [11694.   ],
       [ 5348.   ],
       [ 6338.   ],
       [ 6488.   ],
       [ 6918.   ],
       [ 7898.   ],
       [ 8778.   ],
       [ 6938.   ],
       [ 7198.   ],
       [ 7898.   ],
       [ 7788.   ],
       [ 7738.   ],
       [ 8358.   ],
       [ 9258.   ],
       [ 8058.   ],
       [ 8238.   ],
       [ 9298.   ],
       [ 9538.   ],
       [ 8449.   ],
       [ 9639.   ],
       [ 9989.   ],
       [11199.   ],
       [11549.   ],
       [17669.   ],
       [ 8948.   ],
       [10698.   ],
       [ 9988.   ],
       [10898.   ],
       [11248.   ],
       [16558.   ],
       [15998.   ],
       [15690.   ],
       [15750.   ],
       [ 7775.   ],
       [ 7975.   ],
       [ 7995.   ],
       [ 8195.   ],
       [ 8495.   ],
       [ 9495.   ],
       [ 9995.   ],
       [11595.   ],
       [ 9980.   ],
       [13295.   ],
       [13845.   ],
       [12290.   ],
       [12940.   ],
       [13415.   ],
       [15985.   ],
       [16515.   ],
       [18420.   ],
       [18950.   ],
       [16845.   ],
       [19045.   ],
       [21485.   ],
       [22470.   ],
       [22625.   ]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_test,y_test)

LinearRegression()

In [12]:
y_pred=l1.predict(x_test)
y_pred

array([[ 9823.42268041],
       [17361.75475726],
       [11977.23184522],
       [14669.49330124],
       [15207.94559244],
       [ 9823.42268041],
       [15746.39788365],
       [ 9284.97038921],
       [ 5515.80435079],
       [13054.13642763],
       [17361.75475726],
       [10361.87497162],
       [11977.23184522],
       [15207.94559244],
       [15207.94559244],
       [10361.87497162],
       [11977.23184522],
       [11977.23184522],
       [16823.30246605],
       [ 9823.42268041],
       [14131.04101004],
       [ 7131.1612244 ],
       [16823.30246605],
       [15207.94559244],
       [13054.13642763],
       [ 1746.63831237],
       [10361.87497162],
       [11977.23184522],
       [14131.04101004],
       [16284.85017485],
       [17900.20704846],
       [14131.04101004],
       [ 9823.42268041],
       [16823.30246605],
       [ 7131.1612244 ],
       [17361.75475726],
       [17361.75475726],
       [17361.75475726],
       [ 9823.42268041],
       [ 5515.80435079],
       [17361.75475726]])

In [13]:
y_test

array([[ 6692. ],
       [14489. ],
       [ 9549. ],
       [16430. ],
       [13415. ],
       [ 6695. ],
       [18280. ],
       [18344. ],
       [ 7775. ],
       [ 9988. ],
       [12964. ],
       [ 6918. ],
       [ 7975. ],
       [21105. ],
       [15040. ],
       [ 7299. ],
       [ 8238. ],
       [ 7295. ],
       [34028. ],
       [ 6229. ],
       [ 7957. ],
       [ 8916.5],
       [17710. ],
       [20970. ],
       [11245. ],
       [ 5151. ],
       [ 7198. ],
       [ 8948. ],
       [17669. ],
       [16500. ],
       [13645. ],
       [13950. ],
       [ 6229. ],
       [24565. ],
       [ 8916.5],
       [16558. ],
       [16695. ],
       [15998. ],
       [13845. ],
       [ 7995. ],
       [15580. ]])